#!/bin/bash

Anon_country_set=$(zenity --list --checklist  --column="check" --column="Code" --column="Country" \
            --separator="," --title="ExitNodes" --multiple --text="Выберите страны до" \
false "{au}"  "AUSTRALIA"	\
false "{at}"  "AUSTRIA"	\
false "{cy}"  "CYPRUS"	\
false "{cz}"  "CZECH REPUBLIC"	\
false "{fr}"  "FRANCE"	\
false "{de}"  "GERMANY"	\
false "{hk}"  "HONG KONG"	\
false "{in}"  "INDIA"	\
false "{id}"  "INDONESIA"	\
false "{il}"  "ISRAEL"	\
false "{it}"  "ITALY"	\
false "{jp}"  "JAPAN"	\
false "{kp}"  "KOREA, DEM. PEOPLES REP OF"	\
false "{kr}"  "KOREA, REPUBLIC OF"	\
false "{lu}"  "LUXEMBOURG"	\
false "{mx}"  "MEXICO"	\
false "{no}"  "NORWAY"	\
false "{ru}"  "RUSSIAN FEDERATION"	\
false "{th}"  "THAILAND"	\
false "{tr}"  "TURKEY"	\
false "{ua}"  "UKRAINE"	\
false "{uk}"  "UNITED KINGDOM"	\
false "{us}"  "UNITED STATES"	\
false "{um}"  "UNITED STATES MINOR OUTL.IS."	\
false "{vn}"  "VIET NAM"	\
false "{vi}"  "VIRGIN ISLANDS (USA)"	\
        --height=800 --width=500)

touch /tmp/Anon_country     
echo $Anon_country_set > /tmp/Anon_country 


exit 0;
