#!/bin/bash


while true
do
#меню утилиты
menu=$(zenity --list --text="Функционал"\
        --radiolist --column "Pick" --column "Anonsurf"\
        FALSE  "start"\
        FALSE  "stop"\
        FALSE  "restart"\
        FALSE  "change"\
        True  "status"\
        --height=400 --width=500)
        
if [ $? = 0 ]; then
 
    if [ $menu = "status" ]; then
            IP=$(wget -qO- eth0.me)
            active=$(systemctl status tor | grep -i Active)
            zenity --info --text="Ваш текущий IP адрес: $IP \n\
                    Статус сети Тор \n\
                    $active "\
                    --height=200 --width=200
    elif [ $menu = "change" ]; then
        bash /etc/init.d/Anon_country
        pkexec bash /usr/lib/anonsurf/anondaemon change

    else
        pkexec bash /usr/lib/anonsurf/anondaemon $menu        
    fi

else break ;

fi
done

#сообщение статуса сети Тор
notifi=$(systemctl is-active tor)
zenity --notification  --text="$notifi Tor"

        

exit 0;
