#!/bin/bash
rm -fv /home/$USER/'Рабочий стол'/Anonsurf

$RED
rm -fv /usr/lib/anonsurf/anondaemon
rm -fv /usr/share/applications/anonsurf.desktop
rm -fv /usr/share/applications/Uninstall-Anonsurf.desktop
rm -fv /etc/tor/torrc 
rm -fv /etc/tor/torrc.orig
rm -fv /etc/tor/onion.pac   
rm -fv /etc/systemd/system/anonsurf.service
rm -fv /usr/bin/Anon  
rm -fv /usr/bin/UnAnonsurf
rm -fv /etc/init.d/UnAnDelete
rm -fv /usr/share/pixmaps/anon.png  
rm -fv /etc/init.d/Anon_country
rm -rf /usr/lib/anonsurf/make-torrc
rm -rf /usr/bin/dnstool
rm -rf /lib/systemd/system/anonsurfd.service
rm -rf /etc/systemd/system/cloudflared-proxy-dns.service
rm -rf /usr/local/bin/cloudflared


exit 0;
